version: '2'
services:
    dom-web:
        build: .
        image: stevevega/dom-web:latest
        ports:
          - 80:8080
        volumes:
          - .:/usr/share/nginx/html:ro

    dom-api:
        image: stevevega/dom-api:latest

    redis:
        image: redis:2
